version: '3.7'
services:

  backend:
    build: backend
    ports:
      - "${BACKEND_HOST_PORT}8000"
    volumes:
      - ./:/app
    depends_on:
      - redis
    links:
      - redis:redis_host
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${RUNSERVER:-uvicorn backend.app.api:app --host 0.0.0.0}
    networks:
      - backend-network
    restart: ${DOCKER_RESTART:-no}

  redis:
    image: redis:5
    ports:
      - "6379"
    networks:
      - backend-network

  proxy:
    build: proxy
    ports:
      - "${PROXY_HOST_PORT}80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: b2blue.lfvilella.com
      VIRTUAL_HOST_ALIAS: b2blue.lfvilella.com,www.b2blue.lfvilella.com
      LETSENCRYPT_HOST: b2blue.lfvilella.com,www.b2blue.lfvilella.com
      LETSENCRYPT_EMAIL: vilella.luisfelipe+b2blue.lfvilella.com@gmail.com
    links:
      - backend:backend_api
    networks:
      - backend-network
      - nginx-gateway
    restart: ${DOCKER_RESTART:-no}

networks:
  backend-network:
  nginx-gateway:
      external:
          name: nginx-gateway
