# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup docker containers
      run: |
        docker network create nginx-gateway
        docker-compose build

    - name: Lint with flake8
      run: |
        RUNSERVER='flake8 .' docker-compose run --rm backend

    - name: Test with pytest
      run: |
        RUNSERVER='pytest --cov=./backend/app' docker-compose run --rm backend

    - name: Coverage Report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        RUNSERVER="codecov --token=$CODECOV_TOKEN" docker-compose run --rm backend
