# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup docker containers
      run: |
        docker network create nginx-gateway
        RUNSERVER=/bin/bash docker-compose up --build -d

    - name: Lint with flake8
      run: |
        docker-compose exec backend /bin/bash -c 'flake8 .'

    - name: Test with pytest
      run: |
        docker-compose exec backend /bin/bash -c 'pytest --cov=./backend/app'

    - name: Coverage Report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        docker-compose exec backend /bin/bash -c 'codecov --token="$CODECOV_TOKEN"'

    - name: Set down docker containers
      run: |
        docker-compose down
